name: build

on: [push, pull_request]

jobs:
  jvm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - run: ./gradlew build
      - run: ./gradlew -Ptest-collect -Pcollect-A-H test
      - run: ./gradlew -Ptest-collect -Pcollect-I-N test
      - run: ./gradlew -Ptest-collect -Pcollect-O-Z test
